name: HTML Lint

on:
  push:
    branches:
      - main
      - master

jobs:
  lint-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install htmlhint

      - name: Lint HTML files
        run: npx htmlhint "**/*.html"
